sylius_resource:
    resources:
        akeneo.attribute_type_mapping:
            driver: doctrine/orm
            classes:
                model: Synolia\SyliusAkeneoPlugin\Entity\AttributeTypeMapping
                form: Synolia\SyliusAkeneoPlugin\Form\Type\AttributeTypeMappingType
        akeneo.categories_configuration:
            driver: doctrine/orm
            classes:
                model: Synolia\SyliusAkeneoPlugin\Entity\CategoriesConfiguration
                repository: Synolia\SyliusAkeneoPlugin\Repository\CategoriesConfigurationRepository
        akeneo.api_configuration:
            driver: doctrine/orm
            classes:
                model: Synolia\SyliusAkeneoPlugin\Entity\ApiConfiguration
        akeneo.product_attribute_akeneo:
            driver: doctrine/orm
            classes:
                model: Sylius\Component\Product\Model\ProductAttribute
                repository: Synolia\SyliusAkeneoPlugin\Repository\ProductAttributeRepository
        akeneo.products_configuration:
            driver: doctrine/orm
            classes:
                model: Synolia\SyliusAkeneoPlugin\Entity\ProductsConfiguration
                repository: Synolia\SyliusAkeneoPlugin\Repository\ProductsConfigurationRepository
        akeneo.setting:
            driver: doctrine/orm
            classes:
                model: Synolia\SyliusAkeneoPlugin\Entity\Setting
        sylius.product_filters_rules:
            driver: doctrine/orm
            classes:
                model: Synolia\SyliusAkeneoPlugin\Entity\ProductFiltersRules
                repository: Synolia\SyliusAkeneoPlugin\Repository\ProductFiltersRulesRepository
