sylius_resource:
    resources:
        akeneo.attribute_type_mapping:
            driver: doctrine/orm
            classes:
                model: Synolia\SyliusAkeneoPlugin\Entity\AttributeTypeMapping
                form: Synolia\SyliusAkeneoPlugin\Form\Type\AttributeTypeMappingType
        akeneo.categories_configuration:
            driver: doctrine/orm
            classes:
                model: Synolia\SyliusAkeneoPlugin\Entity\CategorieConfiguration
                repository: Synolia\SyliusAkeneoPlugin\Repository\CategorieConfigurationRepository
        akeneo.api_configuration:
            driver: doctrine/orm
            classes:
                model: Synolia\SyliusAkeneoPlugin\Entity\ApiConfiguration
        akeneo.product_attribute_akeneo:
            driver: doctrine/orm
            classes:
                model: Synolia\SyliusAkeneoPlugin\Model\ProductAttribute
                repository: Synolia\SyliusAkeneoPlugin\Repository\ProductAttributeRepository
        akeneo.product_option_akeneo:
            driver: doctrine/orm
            classes:
                model: Sylius\Component\Product\Model\ProductOption
                repository: Synolia\SyliusAkeneoPlugin\Repository\ProductOptionRepository
        akeneo.product_configuration:
            driver: doctrine/orm
            classes:
                model: Synolia\SyliusAkeneoPlugin\Entity\ProductConfiguration
                repository: Synolia\SyliusAkeneoPlugin\Repository\ProductConfigurationRepository
        akeneo.product_group:
            driver: doctrine/orm
            classes:
                model: Synolia\SyliusAkeneoPlugin\Entity\ProductGroup
        akeneo.setting:
            driver: doctrine/orm
            classes:
                model: Synolia\SyliusAkeneoPlugin\Entity\Setting
        akeneo.product_akeneo:
            driver: doctrine/orm
            classes:
                model: Sylius\Component\Core\Model\Product
                repository: Synolia\SyliusAkeneoPlugin\Repository\ProductRepository
        akeneo.taxon_akeneo:
            driver: doctrine/orm
            classes:
                model: Sylius\Component\Core\Model\TaxonInterface
                repository: Synolia\SyliusAkeneoPlugin\Repository\TaxonRepository
        akeneo.product_taxon_akeneo:
            driver: doctrine/orm
            classes:
                model: Sylius\Component\Core\Model\ProductTaxon
                repository: Synolia\SyliusAkeneoPlugin\Repository\ProductTaxonRepository
        sylius.product_filters_rules:
            driver: doctrine/orm
            classes:
                model: Synolia\SyliusAkeneoPlugin\Entity\ProductFiltersRules
                repository: Synolia\SyliusAkeneoPlugin\Repository\ProductFiltersRulesRepository
