sylius_resource:
    resources:
        akeneo.attribute_type_mapping:
            driver: doctrine/orm
            classes:
                model: Synolia\SyliusAkeneoPlugin\Entity\AttributeTypeMapping
                form: Synolia\SyliusAkeneoPlugin\Form\Type\AttributeTypeMappingType
        akeneo.attribute_akeneo_sylius_mapping:
            driver: doctrine/orm
            classes:
                model: Synolia\SyliusAkeneoPlugin\Entity\AttributeAkeneoSyliusMapping
                form: Synolia\SyliusAkeneoPlugin\Form\Type\AttributeAkeneoSyliusMappingType
        akeneo.categories_configuration:
            driver: doctrine/orm
            classes:
                model: Synolia\SyliusAkeneoPlugin\Entity\CategorieConfiguration
                repository: Synolia\SyliusAkeneoPlugin\Repository\CategorieConfigurationRepository
        akeneo.api_configuration:
            driver: doctrine/orm
            classes:
                model: Synolia\SyliusAkeneoPlugin\Entity\ApiConfiguration
        akeneo.product_configuration:
            driver: doctrine/orm
            classes:
                model: Synolia\SyliusAkeneoPlugin\Entity\ProductConfiguration
                repository: Synolia\SyliusAkeneoPlugin\Repository\ProductConfigurationRepository
        akeneo.product_group:
            driver: doctrine/orm
            classes:
                model: Synolia\SyliusAkeneoPlugin\Entity\ProductGroup
                repository: Synolia\SyliusAkeneoPlugin\Repository\ProductGroupRepository
        akeneo.setting:
            driver: doctrine/orm
            classes:
                model: Synolia\SyliusAkeneoPlugin\Entity\Setting
        sylius.product_filters_rules:
            driver: doctrine/orm
            classes:
                model: Synolia\SyliusAkeneoPlugin\Entity\ProductFiltersRules
                repository: Synolia\SyliusAkeneoPlugin\Repository\ProductFiltersRulesRepository
