services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Synolia\SyliusAkeneoPlugin\:
        resource: '../../*'
        exclude: '../../{Controller,DependencyInjection,Model,Migrations,Payload,Repository,SynoliaSyliusAkeneoPlugin.php}'

    Synolia\SyliusAkeneoPlugin\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    Synolia\SyliusAkeneoPlugin\Menu\AdminMenuListener:
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }
