services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Synolia\SyliusAkeneoPlugin\:
        resource: '../../*'
        exclude: '../../{Controller,DependencyInjection,Model,Migrations,Payload,SynoliaSyliusAkeneoPlugin.php}'

    Synolia\SyliusAkeneoPlugin\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    Synolia\SyliusAkeneoPlugin\Menu\AdminMenuListener:
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }

    Synolia\SyliusAkeneoPlugin\Repository\ProductFiltersRulesRepository:
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@sylius.product_filters_rules_class_metadata'

    sylius.product_filters_rules_class_metadata:
        class: 'Doctrine\Common\Persistence\Mapping\ClassMetadata'
        factory: ['@doctrine.orm.entity_manager', getClassMetadata]
        arguments:
            - '@Synolia\SyliusAkeneoPlugin\Entity\ProductFiltersRules'

    Synolia\SyliusAkeneoPlugin\Repository\ProductConfigurationRepository:
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@sylius.product_configuration_class_metadata'

    sylius.product_configuration_class_metadata:
        class: 'Doctrine\Common\Persistence\Mapping\ClassMetadata'
        factory: ['@doctrine.orm.entity_manager', getClassMetadata]
        arguments:
            - '@Synolia\SyliusAkeneoPlugin\Entity\ProductConfiguration'

    Synolia\SyliusAkeneoPlugin\Repository\CategoryConfigurationRepository:
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@akeneo.category_configuration_class_metadata'

    akeneo.category_configuration_class_metadata:
        class: 'Doctrine\Common\Persistence\Mapping\ClassMetadata'
        factory: ['@doctrine.orm.entity_manager', getClassMetadata]
        arguments:
            - '@Synolia\SyliusAkeneoPlugin\Entity\CategoryConfiguration'

    Synolia\SyliusAkeneoPlugin\Repository\ProductGroupRepository:
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@akeneo.product_group'

    akeneo.product_group:
        class: 'Doctrine\Common\Persistence\Mapping\ClassMetadata'
        factory: ['@doctrine.orm.entity_manager', getClassMetadata]
        arguments:
            - '@Synolia\SyliusAkeneoPlugin\Entity\ProductGroup'

    akeneo.setting_class_metadata:
        class: 'Doctrine\Common\Persistence\Mapping\ClassMetadata'
        factory: ['@doctrine.orm.entity_manager', getClassMetadata]
        arguments:
            - '@Synolia\SyliusAkeneoPlugin\Entity\Setting'
