services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Synolia\SyliusAkeneoPlugin\:
        resource: '../../*'
        exclude: '../../{Controller,DependencyInjection,Model,Migrations,Payload,Task,SynoliaSyliusAkeneoPlugin.php}'

    Synolia\SyliusAkeneoPlugin\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    Synolia\SyliusAkeneoPlugin\Menu\AdminMenuListener:
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }

    Synolia\SyliusAkeneoPlugin\Repository\ProductFiltersRulesRepository:
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@sylius.product_filters_rules_class_metadata'

    sylius.product_filters_rules_class_metadata:
        class: 'Doctrine\Common\Persistence\Mapping\ClassMetadata'
        factory: ['@doctrine.orm.entity_manager', getClassMetadata]
        arguments:
            - '@Synolia\SyliusAkeneoPlugin\Entity\ProductFiltersRules'

    Synolia\SyliusAkeneoPlugin\Repository\ProductsConfigurationRepository:
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@sylius.products_configuration_class_metadata'

    sylius.products_configuration_class_metadata:
        class: 'Doctrine\Common\Persistence\Mapping\ClassMetadata'
        factory: ['@doctrine.orm.entity_manager', getClassMetadata]
        arguments:
            - '@Synolia\SyliusAkeneoPlugin\Entity\ProductsConfiguration'

    Synolia\SyliusAkeneoPlugin\Repository\CategoriesConfigurationRepository:
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@akeneo.categories_configuration_class_metadata'

    akeneo.categories_configuration_class_metadata:
        class: 'Doctrine\Common\Persistence\Mapping\ClassMetadata'
        factory: ['@doctrine.orm.entity_manager', getClassMetadata]
        arguments:
            - '@Synolia\SyliusAkeneoPlugin\Entity\CategoriesConfiguration'
    akeneo.setting_class_metadata:
        class: 'Doctrine\Common\Persistence\Mapping\ClassMetadata'
        factory: ['@doctrine.orm.entity_manager', getClassMetadata]
        arguments:
            - '@Synolia\SyliusAkeneoPlugin\Entity\Setting'
